version: '3.7'
services:
  backup:
    build: ./src
    env_file:
      - stack-back.env
    labels:
      stack-back.volumes: true
      stack-back.volumes.include: 'src'
    networks:
      - default
      - global
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./restic_data:/restic_data
      - ./restic_cache:/cache
      - ./src:/stack-back
  web:
    image: nginx
    labels:
      stack-back.volumes: true
      stack-back.volumes.include: "/tests"
    volumes:
      - ./src/tests:/srv/tests
      - ./.vscode:/srv/code

  mysql5:
    image: mysql:5
    labels:
      stack-back.mysql: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysqldata5:/var/lib/mysql

  mysql8:
    image: mysql:8
    labels:
      stack-back.mysql: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysqldata8:/var/lib/mysql

  mariadb:
    image: mariadb:10
    labels:
      stack-back.mariadb: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mariadbdata:/var/lib/mysql

  postgres:
    image: postgres:11
    labels:
      stack-back.postgres: true
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  mysqldata5:
  mysqldata8:
  mariadbdata:
  pgdata:

networks:
  global:
    external: true
