version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_install:
      - bash scripts/doc/build_doc_pre_work.sh

python:
  install:
    - requirements: requirements/runtime.txt
    - requirements: requirements/docs.txt

sphinx:
  configuration: docs/source/conf.py
