version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/works:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      DATABASE_URL: postgresql://Pollens:Pollens@db:5432/Pollens

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Pollens
      POSTGRES_USER: Pollens
      POSTGRES_DB: Pollens

volumes:
  postgres-data:
