remote_theme: just-the-docs/just-the-docs

# Site settings
title: BlockSeek Documentation
description: "BlockSeek: AI-Powered Trading Agent | Smart, Secure, and Efficient Trading Solutions"
baseurl: "/blockseek"
url: ""
favicon_ico: "/assets/images/favicon.ico"
logo: "/assets/images/logo.svg"

# Theme settings
search_enabled: true
search:
  heading_level: 3
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true

heading_anchors: true
color_scheme: dark

# Enable copy buttons on code blocks
enable_copy_code_button: true

# External navigation links
aux_links:
  "BlockSeek on GitHub":
    - "https://github.com/smashound/blockseek.ai"
  "Join Discord":
    - "https://discord.gg/blockseek"

aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2024 BlockSeek. Distributed under the MIT license."

# Collections for organizing documentation
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_fold: true

# Enable callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow

# Enable mermaid diagrams
mermaid:
  version: "9.1.3"
  # Configure mermaid theme to match site theme
  theme: dark

# Navigation structure
nav_external_links:
  - title: BlockSeek GitHub
    url: https://github.com/smashound/blockseek.ai
    hide_icon: false
    opens_in_new_tab: true
  - title: Discord Community
    url: https://discord.gg/blockseek
    hide_icon: false
    opens_in_new_tab: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/smashound/blockseek.ai"
gh_edit_branch: "main"
gh_edit_source: docs
gh_edit_view_mode: "tree"

# Additional features
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Enable tabs
tabs:
  sync: true

# Enable copy code button
enable_copy_code_button: true

# Enable anchor copy links
heading_anchors: true

# Enable table of contents
toc:
  enabled: true
  h_min: 1
  h_max: 3 