/**:
  ros__parameters:
    # Preprocessing
    max_range: 100.0
    min_range: 0.0
    deskew: true

    # Mapping parameters
    voxel_size: 1.0
    max_points_per_voxel: 20

    # Adaptive threshold
    initial_threshold: 2.0
    min_motion_th: 0.1

    # Registration
    max_num_iterations: 10
    convergence_criterion: 0.001
    max_num_threads: 1

    # Covariance diagonal values
    orientation_covariance: 0.1
    position_covariance: 0.1
