packages:
  - playgrounds/*
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@antfu/eslint-config': ^4.2.1
  '@antfu/ni': ^23.3.1
  '@antfu/utils': ^9.1.0
  '@eslint-react/eslint-plugin': ^1.26.2
  '@shikijs/core': ^2.4.2
  '@shikijs/engine-javascript': ^2.4.2
  '@shikijs/langs': ^2.4.2
  '@shikijs/themes': ^2.4.2
  '@shikijs/types': ^2.4.2
  '@types/node': ^22.13.4
  '@types/react': ^19.0.10
  '@types/react-dom': ^19.0.4
  '@unocss/reset': ^65.5.0
  '@vitejs/plugin-react': ^4.3.4
  '@vitejs/plugin-react-swc': ^3.8.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/tsconfig': ^0.7.0
  '@vueuse/core': ^12.7.0
  bumpp: ^10.0.3
  eslint: ^9.20.1
  lint-staged: ^15.4.3
  pnpm: ^10.4.1
  react: ^19.0.0
  react-dom: ^19.0.0
  shiki: ^2.4.2
  simple-git-hooks: ^2.11.1
  tsx: ^4.19.2
  typescript: ~5.7.3
  unbuild: ^3.3.1
  unocss: ^65.5.0
  vite: ^6.1.0
  vite-plugin-solid: ^2.11.1
  vitest: ^3.0.5
  vue: ^3.5.13
  vue-tsc: ^2.2.2
