# ------------------------------------------------Environment Settings------------------------------------------------#
gpu_id: "0,1,2,3,4,5,6,7"

# -------------------------------------------------Retrieval Settings------------------------------------------------#
# If set the name, the model path will be find in global paths
retrieval_method: "/path/to/retrieval/model"  # name or path of the retrieval model. 
index_path: "/path/to/index" # path to the indexed file
faiss_gpu: True # whether use gpu to hold index
corpus_path: "/path/to/corpus"  # path to corpus in '.jsonl' format that store the documents



