packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/eslint-config': ^4.9.0
    '@antfu/ni': ^24.1.0
    '@modelcontextprotocol/inspector': ^0.6.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.4.3
    nodemon: ^3.1.9
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ~5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
    vue-tsc: ^2.2.8
  nuxt:
    '@nuxt/devtools': ^2.2.1
    '@nuxt/eslint-config': ^1.2.0
    '@nuxt/kit': ^3.16.0
    '@nuxt/module-builder': ^0.8.4
    '@nuxt/schema': ^3.16.0
    '@nuxt/test-utils': ^3.17.2
    nuxt: ^3.16.0
  prod:
    '@modelcontextprotocol/sdk': ^1.7.0
    debug: ^4.4.0
    h3: ^1.15.1
    pathe: ^2.0.3
    unimport: ^4.1.2
    vite-plugin-mcp: workspace
    zod: ^3.24.2
  testing:
    vitest: ^3.0.8
    vitest-package-exports: ^0.1.1
    yaml: ^2.7.0
  types:
    '@types/debug': ^4.1.12
    '@types/node': latest
  utils:
    '@antfu/utils': ^9.1.0
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
