---
- name: Install Agave Solana validator
  hosts: all                                  # Apply to all hosts
  become: yes                                # Elevate privileges for task execution
  roles:
    - check_node                             # Validate the node's readiness
    - configure_ubuntu                       # Configure the Ubuntu environment
    - agave_cli                              # Install Agave CLI
    - solana_validator_bootstrap             # Bootstrap Solana validator
    - monitoring                             # Set up monitoring tools
  vars:
    agave: yes                               # Specify that this is an Agave installation
