before:
  hooks:
    - go mod download

archives:
  - id: default
    builds:
      - autopilot
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

builds:
  - id: autopilot
    dir: pkg/cmd/autopilot
    binary: autopilot
    ldflags:
      - -X main.versionInfo={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  skip: true

announce:
  skip: "true"