defaults:
  - dataset: dl3dv
  - optional dataset/view_sampler_dataset_specific_config: ${dataset/view_sampler}_${dataset}
  - model/encoder: costvolume
  - model/decoder: splatting_cuda
  - model/refiner: svd
  - loss: [mse]

wandb:
  project: mvsplat360
  entity: placeholder
  name: placeholder
  mode: disabled
  id: null

mode: train

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 10
    persistent_workers: true
    batch_size: 4
    seed: 1234
    drop_last: False
  test:
    num_workers: 4
    persistent_workers: false
    batch_size: 1
    seed: 2345
  val:
    num_workers: 1
    persistent_workers: true
    batch_size: 1
    seed: 3456

optimizer:
  lr: 2.e-4
  refiner_lr: 1.e-5
  warm_up_steps: 2000
  # cosine_lr: true
  sched_method: one_cycle

checkpointing:
  load: null
  every_n_train_steps: 1000  # 5000
  save_top_k: 3
  pretrained_model: null
  legacy_support: false
  resume: true

train:
  depth_mode: null
  extended_visualization: false
  print_log_every_n_steps: 1
  eval_model_every_n_val: 2
  eval_save_model: true
  eval_data_length: 999999999
  eval_deterministic: false
  tune_mvsplat: true
  val_log_video: true
  eval_index_path: assets/evaluation_index_re10k.json
  val_log_video_extra: false
  val_log_images_to_video: false
  val_log_projection: true
  val_log_cameras: true

test:
  output_path: outputs/test
  compute_scores: false
  eval_time_skip_steps: 0
  save_image: false
  save_video: false
  save_context: false
  save_combined: false
  save_gt: false
  refiner_overlap: 0
  refiner_loop_times: 1
  save_video_pts_times: 1.
  render_stable_poses: false
  stable_k_size: 15
  save_nn_gt: false
  hack_refine_video_path: null
  hack_refine_video_input_ctx: true

seed: 111123

trainer:
  max_steps: -1
  val_check_interval: 0.5
  gradient_clip_val: 0.5
  num_sanity_val_steps: 2
  accumulate_grad_batches: 1
  precision: 32
  check_val_every_n_epoch: 1
  num_nodes: 1

output_dir: null
use_diff_refinement: false
use_legacy_renderer: false
hack_pure_svd_debug: false
perturb_novel_views: false
