data:
  masks:
    masks_path: '' #scannet200
  camera:
    poses_path: ''
    intrinsic_path: ''
    intrinsic_resolution: [968, 1296]
  depths:
    depths_path: ''
    depths_ext: '.png'
    depth_scale: 1000
  images:
    images_path: ''  
    images_ext: '.jpg'
  point_cloud_path: ''

openmask3d:
  top_k: 5
  multi_level_expansion_ratio: 0.1
  num_of_levels: 3
  vis_threshold: 0.2
  frequency: 10
  num_random_rounds: 10
  num_selected_points: 5

external:
  sam_checkpoint: ''
  sam_model_type: 'vit_h'
  clip_model: 'ViT-L/14@336px'

output:
  experiment_name: 'experiment'
  output_directory: 'output/'
  save_crops: False

gpu:
  optimize_gpu_usage: False