apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "open5gs-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: open5gs-operator
    app.kubernetes.io/part-of: open5gs-operator
  {{- include "open5gs-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}