name: Release
on:
  push:
    tags:
      - 'v*'
env:
  GO_VERSION: 1.22.1

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go Environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 1.26.2
          args: release --clean
        env:
          CGO_ENABLED: 0
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}