name: Code check

on:
  pull_request:
    branches: ["*"]

jobs:
  Brandschutzmassnahmen:
    runs-on: ubuntu-latest
    name: npm lint
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install dependencies
        run: npm ci
      - name: Format
        run: npm run format:check
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
