[package]
name = "fennec-semantics"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-fixer = { path = "../fixer" }
fennec-reporting = { path = "../reporting" }
fennec-interner = { path = "../interner" }
fennec-parser = { path = "../parser" }
fennec-walker = { path = "../walker" }
fennec-span = { path = "../span" }
fennec-ast = { path = "../ast" }
fennec-names = { path = "../names" }
fennec-source = { path = "../source" }
fennec-symbol-table = { path = "../symbol-table" }
serde = { workspace = true }
