[package]
name = "fennec-walker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-ast = { path = "../ast" }
paste = { workspace = true }
