version: "3.8"
services:
  app:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../..:/app
      - /app/node_modules
      - /app/.next
      - prisma-data:/app/prisma
    environment:
      - NODE_ENV=development
      - DATABASE_URL=file:/app/prisma/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=development_secret
    command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"

volumes:
  prisma-data:
