services:
  zotifarrr:
    image: zotifarrr
    ports:
      - "7070:7070"
    volumes:
      - "./credentials:/app/credentials"
      - "./downloads:/app/downloads/music" # <-- change this mapping for your music library directory
    restart: unless-stopped
