name: Code Checking

on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
jobs:
  code-checking:
    name: Code Compliance Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run ESLint to check code
      - name: Run ESLint
        run: npm run lint
