site_name: Awesome-MLSys-Blogger
site_url: https://MLSys-Learner-Resources.github.io/Awesome-MLSys-Blogger/

repo_name: Awesome-MLSys-Resources
repo_url: https://github.com/MLSys-Learner-Resources/Awesome-MLSys-Blogger

theme:
  name: material
  palette:
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - header.autohide
    - content.action.zoom

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.details

nav:
  - About: about.md
  - Home: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MLSys-Learner-Resources/Awesome-MLSys-Blogger
      name: View on GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:yin00486@umn.edu

  logo: images/logo.png
  favicon: images/favicon.ico