name: svd
config_path: config/model/refiner/diffusion_configs/svd_wo_mb_fps.yaml
ckpt_path: checkpoints/svd.safetensors
use_same_noise_fwd: false
verbose: true
cond_aug: 0.02
motion_bucket_id: null
fps_id: null
fit_ckpt: true
svd_num_steps: 25
svd_num_frames: 14
svd_clip_cond_type: concate
test_first_stage: false
gs_feat_scale_factor: 0.125
en_and_decode_n_samples_a_time: null
test_time_attn_num_splits: null
weight_train_gs_feat_via_enc: 0.
train_gs_feat_enc_type: gs_rendered
