[source]
paths = ["src"]
includes = []
excludes = []

[linter]

# This rule is disabled by default because it is experimental, enable it if you want to have a peek at it.
# [[linter.rules]]
# name = "comment/docblock-syntax"
# level = "Warning"
