version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - wildberry-network

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-wildberry}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-wildberrypass}
      - POSTGRES_DB=${POSTGRES_DB:-wildberry}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - wildberry-network

networks:
  wildberry-network:
    driver: bridge

volumes:
  postgres_data:
