[package]
name = "fennec-linter"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
fennec-fixer = { path = "../fixer" }
fennec-semantics = { path = "../semantics" }
fennec-reporting = { path = "../reporting" }
fennec-docblock = { path = "../docblock" }
fennec-interner = { path = "../interner" }
fennec-span = { path = "../span" }
fennec-ast = { path = "../ast" }
fennec-names = { path = "../names" }
fennec-source = { path = "../source" }
fennec-symbol-table = { path = "../symbol-table" }
fennec-walker = { path = "../walker" }
fennec-parser = { path = "../parser" }
fennec-casing = { path = "../casing" }
ahash = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
toml = { workspace = true }
