version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/works:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      DATABASE_URL: postgresql://BeeSync:BeeSync@db:5432/BeeSync

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: BeeSync
      POSTGRES_USER: BeeSync
      POSTGRES_DB: BeeSync

volumes:
  postgres-data:
