apiVersion: net.gradiant.org/v1
kind: Open5GS
metadata:
  name: open5gs-2
spec:
  hss:
    enabled: false

  mme:
    enabled: false

  pcrf:
    enabled: false

  smf:
    config:
      pcrf:
        enabled: false

  sgwc:
    enabled: false

  sgwu:
    enabled: false

  amf:
    config:
      guamiList:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          amf_id:
            region: 2
            set: 1
      taiList:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          tac: [1]
      plmnList:
        - plmn_id:
            mcc: "999"
            mnc: "70"
          s_nssai:
            - sst: 1
              sd: "0x111111"

  nssf:
    config:
      nsiList:
        - uri: ""
          sst: 1
          sd: "0x111111"

  webui:
    enabled: false
  populate:
    enabled: false

