[package]
name = "rust-stakeholder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
colored = "3.0.0"
console = "0.15.11"
ctrlc = "3.4.5"
indicatif = "0.17.11"
rand = "0.9.0"
