name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: 20

      - name: Check package version
        id: check
        uses: 'EndBug/version-check@36ff30f37c7deabe56a30caa043d127be658c425' # v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff-search: true

      - name: Create release
        uses: 'ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87' # v1
        if: ${{ steps.check.outputs.changed == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: v${{ steps.check.outputs.version}}
          name: v${{ steps.check.outputs.version}}
